FROM alpine


# установка зависимостей
# символ астериск ("*") используется для того чтобы по возможности 
# скопировать оба файла: package.json и package-lock.json
# COPY package*.json ./


RUN apk add git\
  && apk add npm\
  && git clone https://github.com/akerbs/docker_web_app_ssh.git \
  && cd  docker_web_app_ssh \
  && npm install
# Если вы создаете сборку для продакшн
# RUN npm ci --only=production

# создание директории приложения
WORKDIR  ./docker_web_app_ssh


# копируем исходный код
# COPY . .  


CMD npm start

EXPOSE 3000